package com.docsapp.chatbot.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private Long id;
    private String chatBotName;
    private String message;
    private String emotion;
    private Long chatBotID;
    private Boolean isOwner = false;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String chatBotName, String message, String emotion, Long chatBotID, Boolean isOwner) {
        this.id = id;
        this.chatBotName = chatBotName;
        this.message = message;
        this.emotion = emotion;
        this.chatBotID = chatBotID;
        this.isOwner = isOwner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChatBotName() {
        return chatBotName;
    }

    public void setChatBotName(String chatBotName) {
        this.chatBotName = chatBotName;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getEmotion() {
        return emotion;
    }

    public void setEmotion(String emotion) {
        this.emotion = emotion;
    }

    public Long getChatBotID() {
        return chatBotID;
    }

    public void setChatBotID(Long chatBotID) {
        this.chatBotID = chatBotID;
    }

    public Boolean getIsOwner() {
        return isOwner;
    }

    public void setIsOwner(Boolean isOwner) {
        this.isOwner = isOwner;
    }

}
